export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILED:'LOGOUT_FAILED'
} 
export const userConstants = {
    GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
    GET_USER_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE',
    ADD_USER_ADDRESS_REQUEST: 'ADD_USER_ADDRESS_REQUEST',
    ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
    ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_FAILURE',
    CONFIRM_ORDER_REQUEST:'CONFIRM_ORDER_REQUEST',
    CONFIRM_ORDER_SUCCESS:'CONFIRM_ORDER_SUCCESS',
    CONFIRM_ORDER_FAILURE:'CONFIRM_ORDER_FAILURE',
    GET_USER_ORDER_REQUEST:'GET_USER_ORDER_REQUEST',
    GET_USER_ORDER_SUCCESS:'GET_USER_ORDER_SUCCESS',
    GET_USER_ORDER_FAILURE:'GET_USER_ORDER_FAILURE'
}
export const productConstants = {
    GET_PRODUCT_LIST_SUCCESS: 'GET_PRODUCT_LIST__SUCCESS',
    GET_PRODUCT_LIST_REQUEST:  'GET_PRODUCT_LIST_REQUEST',
    GET_PRODUCT_LIST_FAILURE: ' GET_PRODUCT_LIST_FAILURE',
    GET_PRODUCT_DETAILS_SUCCESS: 'GET_PRODUCT_DETAILS_SUCCESS',
    GET_PRODUCT_DETAILS_FAILURE: 'GET_PRODUCT_DETAILS_FAILURE',
    GET_PRODUCT_DETAILS_REQUEST: 'GET_PRODUCT_DETAILS_REQUEST'
}
export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    CATEGORY_ADDITION_REQUEST:'CATEGORY_ADDITION_REQUEST',
    CATEGORY_ADDITION_SUCCESS:'CATEGORY_ADDITION_SUCCESS',
    CATEGORY_ADDITION_FAILURE:'CATEGORY_ADDITION_FAILURE'
}
export const pageConstants = {
    GET_PAGE_REQUEST:'GET_PAGE_REQUEST',
    GET_PAGE_SUCCESS:'GET_PAGE_SUCCESS',
    GET_PAGE_FAILURE:'GET_PAGE_FAILURE'
}
export const cartConstants = {
    ADD_TO_CART_REQUEST:'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS:'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE:'ADD_TO_CART_FAILURE',
    RESET_CART:'RESET_CART'
}