export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILED:'LOGOUT_FAILED'
} 
export const userConstant = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILED: 'SIGNUP_FAILED'
}
export const productConstants = {
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE'
}
export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    CATEGORY_ADDITION_REQUEST:'CATEGORY_ADDITION_REQUEST',
    CATEGORY_ADDITION_SUCCESS:'CATEGORY_ADDITION_SUCCESS',
    CATEGORY_ADDITION_FAILURE:'CATEGORY_ADDITION_FAILURE',
    UPDATE_CATEGORIES_REQUEST:'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS:'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILURE:'UPDATE_CATEGORIES_FAILURE',
    DELETE_CATEGORIES_REQUEST:'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS:'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE:'DELETE_CATEGORIES_FAILURE'
}
export const pageConstants = {
    CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE:'CREATE_PAGE_FAILURE'
}